### PR TITLE
Render README from refdoc

### LINKED ISSUE #2130: Generate readme from refdoc.
Right now ref docs are generated with 
- entrypoint: Basic install instruction
- options: Emitter options
- data types
- operations, interfaces
- decorators
- etc.

Would be good to have a readme generated from it as well might. Might need an extra `guide.md` that gets merged in the entryopoint of the doc and in the readme 

Readme should probably include those concactenated:
- entrypoint
- guide.md
- options
- decorators

### LINKED ISSUE #2239: Share Open API type across specs
Hi folks,

Forgive me if this is possible and I'm just bad at reading the docs. I currently have a Node.js 'front door' service/public API that calls into a Go core service. The APIs on the Go service are mostly not public, and are defined as OpenAPI v2 specifications (and protos if that in any way makes this easier).

For a limited subset of complex types, I want to 'forward' the types from the Go service's Open API definition into the public API, as a property of another type. Simplified, it would look something like this:

```
model Service {
  @visibility("read", "update")
  @path
  id: string;
  customerId: string;
  name: string;
  metadata?: TypeFromOtherAPISpec;
}
```

Ideally, there would be to make an almost 'virtual type' from another open API specification, something like:
```
model Service {
  @visibility("read", "update")
  @path
  id: string;
  customerId: string;
  name: string;
 @fromOpenApi("/filePathToOtherTypeInOpenApiSchemaFormat")
  metadata?: unknown;
}
```

Is there a good way to do something like this? Otherwise I can make a build step to do a bunch of string replacement.

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix #2130 

Generate the README.md for typespec libraries automatically using the subset of the content as what gets included in the ref doc

To achieve this I reoganized the markdown rendering to be able to provide a reusable system that can be cusomized for different markdown engines.

- The markdown renderer will render a markdown compatible with Github Flavored Markdown. 
- The docusuaurs rendererer extends the markdown renderer and include a few extra metadata.

### CODE REVIEW

**Comment by timotheeguerin** [comment]
PR in typespec-azure uptaking this change https://github.com/Azure/typespec-azure/pull/3374

**Review by mikekistler — APPROVED** [review]
Looks good. 👍

**Review by markcowl — COMMENTED** [review]
@timotheeguerin   Please fix the minor issue in the Azure PR, and this one looks good

**Comment by timotheeguerin** [comment]
> @timotheeguerin Please fix the minor issue in the Azure PR, and this one looks good

seems like a different casing in the README.md, I just updated to match the others but the tool should probably allow a different name if user prefer in the future.

**Pull request merged**
