### PR TITLE
fix checker failure referencing property of template parameter.

### LINKED ISSUE #1280: Referencing property of template parameter that extends something that has said property fails
```cadl
model Discriminated {
  kind: string;
};

model OpenAiList<T extends Discriminated> {
  broken: T.kind;
  works: Discriminated.kind;
}
```

[playground](https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgRGlzY3JpbWluYXRlZCB7CiAga2luZDogc3RyaW5nOwp9OwoKxipPcGVuQWlMaXN0PFQgZXh0ZW5kc84%2FPsVAYnJva2VuOiBULsRKOwogIHdvcmtzOs4sxx19)

### PR DESCRIPTION
**Pull request by jianyexi**
fix https://github.com/microsoft/cadl/issues/1280

see fixed [playground](https://cadlplayground.z22.web.core.windows.net/prs/1543/?c=bW9kZWwgRGlzY3JpbWluYXRlZCB7DQogIGtpbmQ6IHN0cmluZzsNCn07DQoNCsYuT3BlbkFpTGlzdDxUIGV4dGVuZHPOQz7GRGJyb2tlbjogVC7ETjvEE3dvcmtzOs4uyB59)

### CODE REVIEW

**Comment by bterlson** [comment]
I believe there are a number of cases right now where a template parameter with constraints doesn't work as you might expect which we have hacked around in some cases by making a template parameter effectively behave as `any`. A generalized fix we have discussed is checking templates with T instantiated as its constraint when present, which should hopefully address most if not all of these issues?

A code sample that I believe should work is e.g.:

```
model OpenAiList<T extends {kind: "string"}> {
  broken: T.kind;
  works: Discriminated.kind;
}
```

**Comment by jianyexi** [comment]
@bterlson Thanks, do you mean all the TypeReferences of the T's properties in the template should be checked with the instantiated constraint model?

**Comment by bterlson** [comment]
I think that's what I mean, in this case. High level, I don't want to fix this piece by piece but attack the whole problem space with a better approach like type checking template parameters as their constraints when constrained, and otherwise as `any` as we do today.

I am not sure if we need a design discussion for this as it feels like an implementation detail, but maybe @nguerrera can share his thoughts here?

**Comment by nguerrera** [comment]
This makes sense to me and unless there's a downside I'm not seeing, I'm OK treating it as implementation detail/bug fix with broader scope. @jianyexi Do you have enough info to try this?

> checking template parameters as their constraints when constrained, and otherwise as any as we do today

**Comment by jianyexi** [comment]
I will try to fix it. Seems we need to resolve symbol for the template parameter constraint expression, as it might not always have a symbol?

**Comment by jianyexi** [comment]
@nguerrera  I will try to fix it. Seems we need to resolve symbol for the template parameter constraint expression node, as I found it doesn't have a symbol when the constraint is a model expression.

**Comment by jianyexi** [comment]
@bterlson do we need to support nested property reference, like 
``` cadl
model A {
  b: {
     c: string
  }
}
model B {
  d: A.b.c
}
```
As I found, currently it's not supported by the compiler.

**Comment by jianyexi** [comment]
@nguerrera @bterlson could you review it again?

**Comment by bterlson** [comment]
Sorry for missing the pings! You can always feel free to ping me on teams directly too.

Re: this PR, this was not the fix I had in mind, it misses the high level part. I continue to worry that this is a very narrow scope hack to address this one use case but runs the risk of having a long bug tail and leaves other things that should work on the table.

I imagined the fix would be more along the lines of updating checkTemplateParameterDeclaration to treat `T` as its constraint type (likely with some "this is a template parameter declaration" flag). This would allow the above scenario to work, as well as any other cases where template parameters need to behave as if they were the constraint type (e.g. if the constraint is an array, I should be able to treat T as an array). It would also allow us to remove the special case handling we're currently doing when passing a T as a parameter to another template with a constraint.

Can I better understand the priority behind this request? If this is low-ish priority I think we should do the more general fix. If this is something we need to work soon I am ok taking this fix with the understanding that we'll fix it up later.

**Comment by jianyexi** [comment]
Thanks for the comments, it's helpful, I will try to fix the do more general fix.  Also, could you give your perspective of this question https://github.com/microsoft/cadl/pull/1543#issuecomment-1418465520.

**Comment by jianyexi** [comment]
@bterlson  @nguerrera I've updated PR to return constraint from the check of template parameter, could you help review this PR?

**Comment by timotheeguerin** [comment]
Replacement https://github.com/microsoft/typespec/pull/2101

**Pull request closed without merging**
