### PR TITLE
Use 1ES pools in all pipelines

### PR DESCRIPTION
**Pull request by mikeharder**
- Also set vmImage where missing

### CODE REVIEW

**Comment by nguerrera** [comment]
@allenjzhang IIRC, you did this before and reverted some of them but I do not recall the reason for the revert. Is that right? Do you remember why we reverted if so?

**Review by nguerrera — APPROVED** [review]
LGTM, but wait for @allenjzhang to see if there wasn't something more to why he didn't do these ones.

**Comment by timotheeguerin** [comment]
I think there was some issue with the wrong version of visual studio available preventing the packaging of of hte visual studio extension(or something like that)

But guessing that if hte PR ci is passing now this has been resolved. We should just watch that the main branch CI doesn't fail after merging.

**Comment by timotheeguerin** [comment]
@mikeharder no the fact that the PR is passing I think is a good enough sign to me that it was resolved.

**Review by timotheeguerin — APPROVED** [review]

**Pull request merged**
