### PR TITLE
Fix `ResourceCreateModel` template

### LINKED ISSUE #2604: @visibility("create") has no effect
Property using @visibility("create") are not exported in any model.

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdCI7CgpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKfSkKbmFtZXNwYWNlIERlbW%2FHGzsKCnVzaW5nIFR5cGVTcGVjLkh0dHA70BVSZXN0OwoKbW9kZWwgx13EcEBrZXkgaWQ6IHN0cmluZzvEE3Zpc2liaWxpdHkoInJlYWQiKSBwcm9wU2hvdWxkQmVJbkdFVDogaW50MzLRMGNyZWF0ZdEyUE9T2TN1cGTVM0FUQ0jLNMweRXZlcnl3aGVyZckhfQoKQGVycm9y5wDkRcQM5QDjY29kyicgIG1lc3NhZ2XqAPJ9CgppbnRlcmbkAVrmARvnAVwgZXh0ZW5kcyBSZXNvdXJjZeQBR8UJT3BlcmF0aW9uczzGMizGcT4gewp9Cg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D)

### PR DESCRIPTION
**Pull request by tjprescott**
Fix #2604.

### CODE REVIEW

**Comment by tjprescott** [comment]
[Playground](https://cadlplayground.z22.web.core.windows.net/prs/2663/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQrSGnJlc3TEGg0KQHNlcnZpY2Uoew0KICB0aXRsZTogIldpZGdldCBTxhwiLA0KfSkNCm5hbWVzcGFjZSBEZW1vxx3FRnVzaW5nIFR5cGVTcGVjLkh0dHA70RZSZXN0xS5tb2RlbCDHZMV4QGtleSBpZDogc3RyaW5nO8UUdmlzaWJpbGl0eSgicmVhZCIpIHByb3BTaG91bGRCZUluR0VUOiBpbnQzMtIxY3JlYXRl0TNQT1PaNHVwZNU0QVRDSMw1zB9FdmVyeXdoZXJlyiJ95QFZZXJyb3LoAO1FxA3mAOxjb2TLLCAgbWVzc2FnZesA%2FMVAaW50ZXJm5AFt5gEp5wFvIGV4dGVuZHMgUmVzb3VyY2XkAVfFCU9wZXJhdGlvbnM8xjIsxnY%2BxHd9DQo%3D&e=%40typespec%2Fopenapi3&options=%7B%7D) showing this fixes the issue.

Whether this is the solution we want is another question.

**Comment by timotheeguerin** [comment]
I don't really get what that DefaultKeyVisibilty template does but wouldn't using the `@withvisibilkity` decorator resolve this problem without introducing a new one

https://cadlplayground.z22.web.core.windows.net/prs/2663/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7DQrSGnJlc3TEGg0KQHNlcnZpY2Uoew0KICB0aXRsZTogIldpZGdldCBTxhwiLA0KfSkNCm5hbWVzcGFjZSBEZW1vxx3FRnVzaW5nIFR5cGVTcGVjLkh0dHA70RZSZXN01hbEBW91csdNbW9kZWwg5wCD5QCXQGtleSBpZDogc3RyaW5nO8UUdmlzaWJpbGl0eSgicmVhZCIpIHByb3BTaG91bGRCZUluR0VUOiBpbnQzMtIxY3JlYXRl0TNQT1PaNHVwZNU0QVRDSMw1zB9FdmVyeXdoZXJlyiJ95QF4ZXJyb3LoAO1FxA3mAOxjb2TLLCAgbWVzc2FnZesA%2FMVALy%2FEJGVyZuQBj%2BYBLOcBkSBleHRlbmRzIOgBVekBXk9wZXJhdGlvbnM8xjIsxnk%2BxHovLyDFWQ0KQHdpdGhW8wEt7gGbQ8UWIGlz6wGrfQ%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D

**Comment by tjprescott** [comment]
@timotheeguerin updated. Please take another look.

**Review by timotheeguerin — CHANGES_REQUESTED** [review]
Actually is there not a test to add for this?

**Comment by tjprescott** [comment]
> Actually is there not a test to add for this?

Added

**Review by timotheeguerin — APPROVED** [review]

**Pull request merged**
