### PR TITLE
Update `@typespec/migrate` to work with updated semver package

### LINKED ISSUE #2195: [@typespec/migrate] TypeError: Invalid Version: 0.38
## Repro Steps
```
$ npm i @typespec/compiler@0.46.0 @typespec/migrate@0.46.0

$ npx tsp init
<accept all defaults>

$ npx @typespec/migrate
TypeSpec migration tool v0.46.0

Current Typespec version latest.
TypeError: Invalid Version: 0.38
    at new SemVer (/home/mharder/tmp/migrate-test-2/node_modules/semver/classes/semver.js:38:13)
    at compare (/home/mharder/tmp/migrate-test-2/node_modules/semver/functions/compare.js:3:3)
    at Module.gt (/home/mharder/tmp/migrate-test-2/node_modules/semver/functions/gt.js:2:29)
    at main (file:///home/mharder/tmp/migrate-test-2/node_modules/@typespec/migrate/dist/src/cli.js:50:20)
```

Likely introduced by in #1888.  `semver` cannot parse version strings like `"0.38"`.  It can only parse `"0.38.0"`.

### PR DESCRIPTION
**Pull request by tjprescott**
Fix #2195.

### CODE REVIEW

**Review by mikeharder — APPROVED** [review]

**Comment by mikeharder** [comment]
@tjprescott, @timotheeguerin: Think it's worth hotfixing this?  I know at least one customer was blocked by it.

**Comment by timotheeguerin** [comment]
I’m still oof today so can’t double check but I don’t think this is blocking when migrating they can always provide the —version=old version to be explicit

**Comment by mikeharder** [comment]
> I’m still oof today so can’t double check but I don’t think this is blocking when migrating they can always provide the —version=old version to be explicit

If you're talking about the `--tspVersion` option, I don't think it's a workaround:

```
$ npx @typespec/migrate --tspVersion 0.46.0
TypeSpec migration tool v0.46.0

Current Typespec version 0.46.0.
TypeError: Invalid Version: 0.38
```

**Comment by mikeharder** [comment]
I would recommend hotfixing this but it's up to the TypeSpec team.

**Comment by timotheeguerin** [comment]
If you pass without the patch —tspVersion 0.38

**Comment by mikeharder** [comment]
> If you pass without the patch —tspVersion 0.38

```
$ npx @typespec/migrate --tspVersion 0.38
TypeSpec migration tool v0.46.0

Current Typespec version 0.38.
TypeError: Invalid Version: 0.38
```

**Comment by timotheeguerin** [comment]
Hhm then I guess probably worthy an hot fix

**Comment by mikeharder** [comment]
@timotheeguerin: Should I open an issue to request hotfixing this?  Is there a special process to request hotfixes?

**Comment by tjprescott** [comment]
cc @markcowl

**Pull request merged**
