### PR TITLE
Custom output viewer

### PR DESCRIPTION
**Pull request by timotheeguerin**
Provide a way to pass a custom program viewer to the playground. This should enable scnearios like having a `TypeSpec UI` viewer similar to swagger UI.
Moved the viewer selection to be some vertical tabs with icons to the right instead

File output viewer
image

Type graph viewer

image

Also fix issues related to the playground build not validating the typesript

### CODE REVIEW

**Review by bterlson — APPROVED** [review]
This is 10x better for sure.

**Comment by ravanscafi** [comment]
I apologize for the dumb question, but where's the Swagger UI now? How do I visualize it?
@timotheeguerin @bterlson

**Comment by timotheeguerin** [comment]
hhm @ravanscafi that's a good catch seems like something got broken in the middle of this. I'll look into it

**Comment by timotheeguerin** [comment]
Fix here https://github.com/microsoft/typespec/pull/3552

**Pull request merged**
