### PR TITLE
Minor rename follow-up

### PR DESCRIPTION
**Pull request by allenjzhang**

### CODE REVIEW

**Review by m-nash — APPROVED** [review]

**Review by markcowl — APPROVED** [review]

**Comment by markcowl** [comment]
The build for this is here: https://dev.azure.com/azure-sdk/public/_build/results?buildId=2197145&view=results

minor changelog issue.  It looks like the notifications are not being redirected

**Review by nguerrera — APPROVED** [review]

**Comment by nguerrera** [comment]
You may need to close and reopen to get it to stop requiring old "cadl - Verify PR"

**Pull request closed without merging**
