### PR TITLE
Playground version picker

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix https://github.com/microsoft/typespec/issues/2044

image

### CODE REVIEW

**Review by daviwil — APPROVED** [review]
Looks good as far as I can tell.  Does this mean we need to publish versioned directories of build artifacts on the playground site so that earlier versions can be imported?

**Comment by timotheeguerin** [comment]
> Looks good as far as I can tell. Does this mean we need to publish versioned directories of build artifacts on the playground site so that earlier versions can be imported?

If we do actually want to allow older version than 0.49 yeah, we should be able to write a script that download each older  version of our package tgz, decompress it run the bunlder on it and upload it but I am not sure this is really needed.

**Comment by daviwil** [comment]
Ahhh yeah, I wasn't even talking about historical versions, just the strategy going forward.

**Comment by timotheeguerin** [comment]
Oh for next version it is already taken care of, it will publish automatically if the version has not been published(in the same way we publish to npm) I did that a week or 2 ago https://github.com/microsoft/typespec/pull/2587

**Review by bterlson — APPROVED** [review]

**Pull request merged**
