### PR TITLE
Typespec Generation for Empty Schema #4923

### LINKED ISSUE #4923: OpenAPI3 Converted produce invalid typespec for empty schema
```yaml
openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags: []
paths: {}
components: 
  schemas:
    Foo: {}
```

produce invalid typespec with `scalar extends unknown`

[Playground Link](https://typespec.io/playground/?c=CiAgaW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI71RtvcGVuYXBp3h4zIjsKCiAgdXNpbmcgSHR0cMQuxg5PcGVuQVBJxSAKICAgIEBzZXJ2aWNlKHvFDyAgdGl0bGU6ICIoxQkpIsUXfSnGLWluZm8oeyJ2ZXJzaW9uIjoiMC4wLjAixx8KbmFtZXNwYWNlxkbFZnNjYWxhciBGb28gZXh0ZW5kcyB1bmtub3duxR%2FFBCAg&e=%40typespec%2Fopenapi3&options=%7B%7D)

### PR DESCRIPTION
**Pull request by JamesChen-us**
fix #4923

### CODE REVIEW

**Comment by JamesChen-us** [comment]
> @JamesChen-us please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by JamesChen-us** [comment]
@microsoft-github-policy-service agree

**Review by chrisradek — COMMENTED** [review]
@JamesChen-us Thank you for creating this pull request and addressing the CI failures! I just had one minor comment on the changelog notes, but otherwise think this looks great!

**Review by chrisradek — APPROVED** [review]

**Comment by chrisradek** [comment]
@JamesChen-us Thank you again for your contribution! Merging this now - this will be included in the next release!

**Pull request merged**
