### PR TITLE
Upgrade to prettier 3.1

### PR DESCRIPTION
**Pull request by timotheeguerin**
https://prettier.io/blog/2023/11/13/3.1.0

### CODE REVIEW

**Comment by tjprescott** [comment]
Why do we want to do this? The blog post says it is experimental.

**Comment by timotheeguerin** [comment]
> Why do we want to do this? The blog post says it is experimental.

THere is just a new flag for some new ternary formatting that is experimental, the package itself isn't

**Comment by tjprescott** [comment]
> THere is just a new flag for some new ternary formatting that is experimental, the package itself isn't

From the diff in the PR it seems that flag is on. Why do we need to update prettier in the first place?

**Comment by timotheeguerin** [comment]
There is 2 changes in the changelog to ternary. 1 it retrinroduce the nesting which is the change you are seeing now. We can also enable the experimental flag which we don't which would flatten it back  and move more things inline in some cases.

For why to update, 1 is why not? it is always good to be up to date with dependencies and not have years of backlog which we endup having a rush to fix something one day. 2nd there is currently an issue with prettier that fail install on windows randomly so hopefully this gets fixed here.

**Review by tjprescott — APPROVED** [review]

**Pull request merged**
