### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by mario-guerra**
Adding myself as a code owner so I can stay on top of issues and PRs filed.

### CODE REVIEW

**Comment by mario-guerra** [comment]
@timotheeguerin @allenjzhang @markcowl can one of you please approve this PR?

**Comment by mario-guerra** [comment]
@allenjzhang ping, plz approve.

**Comment by timotheeguerin** [comment]
@mario-guerra do you need to be code owner if your goal is just to be able to watch PRs?

**Comment by mario-guerra** [comment]
@timotheeguerin I want to be notified when issues, discussions, and PRs are filed, is there a way to enable that without being a code owner?

**Comment by timotheeguerin** [comment]
You should able to watch the repo and configure more or less notifcations i believe
image

**Review by allenjzhang — APPROVED** [review]

**Comment by mario-guerra** [comment]
Thanks @timotheeguerin I didn't know that, I've signed up for the notifications I want.

**Comment by timotheeguerin** [comment]
so can we close that?

**Pull request closed without merging**
