### PR TITLE
fix useAuth decorator link to authentication section

### PR DESCRIPTION
**Pull request by rahimi-ali**
Fix the link syntax and target

### CODE REVIEW

**Review by markcowl — CHANGES_REQUESTED** [review]
It looks like the linter needs to be executed to pass ci.  Most likely this is a subtle change in the linter for markdown files

**Comment by daviwil** [comment]
@rahimi-ali @markcowl I fixed the issue preventing CI from passing but it seems that it's now triggered the CLA notice.  Let me know if you have trouble signing it (or if you can't), @rahimi-ali and I can reopen this PR myself.  Thanks!

**Review by daviwil — APPROVED** [review]

**Comment by rahimi-ali** [comment]
> @rahimi-ali please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by daviwil** [comment]
Thanks for the contribution @rahimi-ali!

**Pull request merged**
