### PR TITLE
Fix handling decorators for union variants in JSONSchema emitter

### LINKED ISSUE #3391: [Bug]: JSONSchema emitter ignores decorator metadata is ignored on union variants
### Describe the bug

It seems like decorator metadata I attach to a union variant it gets ignored. For example, if I write documentation with `@doc` or a doc comment it's silently ignored. I tried looking for a workaround with a custom decorator, but I couldn't find one.

image

### Reproduction

[Playground link](https://typespec.io/playground?c=aW1wb3J0ICJAdHlwZXNwZWMvanNvbi1zY2hlbWEiOwoKdXNpbmcgVHlwZVNwZWMuSnNvblPFHTsKCkDELMYOCnVuaW9uIEZvbyB7CiAgQGRvYygiZG9jIHRleHQiKcQTc3VtbWFyeSgixwnLG2V4dGVuc2lvbigieC1rZXkiLCDEaTwieC12YWx1ZSI%2BxCdiYXI6IHN0cmluZwp9CgoK&e=%40typespec%2Fjson-schema&options=%7B%7D)

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that request the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/Microsoft/typespec/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### PR DESCRIPTION
**Pull request by Veetaha**
Fixes #3391

Also refactored a minor problem of using a deprecated reexport of `DuplicateTracker`, not it's referenced from `@typespec/compiler/utils` directly, and another small typo.

### CODE REVIEW

**Comment by Veetaha** [comment]
@microsoft-github-policy-service agree

**Review by timotheeguerin — APPROVED** [review]
This looks great, thanks for your contribution!

**Pull request merged**
