### PR TITLE
Add madeRequired decorator and tests

### LINKED ISSUE #2731: Missing @madeRequired decorator for versioning
I have a datamodel that changed from being optional to being required in a newer version.
There is a nice [`@madeOptional` decorator](https://microsoft.github.io/typespec/standard-library/versioning/reference/decorators#@TypeSpec.Versioning.madeOptional), but there is no `@madeRequired` decorator.
There are some workarounds but they do not exactly generate the wanted results.
Is this something that can be easily added?

### PR DESCRIPTION
**Pull request by borrrden**
Hopefully I got all the places I needed to get and added enough tests.  My methodology was pretty much "Look at what madeOptional does, and do the opposite"

Closes #2731

### CODE REVIEW

**Comment by borrrden** [comment]
@microsoft-github-policy-service agree

**Review by timotheeguerin — CHANGES_REQUESTED** [review]
Thanks a lot for the contribution, from the pure decorator point of view this looks good.
However this current implementation will mot allow a property go go `optional -> required -> optional` multiple times(or the other way around). 

This is something we can do today with `@added` and `@removed`.

What we basically need is to create the same availability timeline but for the requireness of a property and have a `isOptionalAtVersion` helper.

**Comment by borrrden** [comment]
Not sure I can work out all of that from an outside view.  I understand the problem but not enough of the semantics of how this all works just yet.  I'll have a look and see what I can reason about given what the added and removed decorators do.

**Comment by borrrden** [comment]
Also what's with the "undocumented changes"?  It doesn't seem to show me any changes to document....

**Comment by borrrden** [comment]
I thought I had this down but the PR checks apparently have ME down instead :p

**Review by timotheeguerin — APPROVED** [review]
@borrrden talked with the team and we'll file a follow up issue to add the scenarios I was talking about above as you already cover the 99% use case.

**Pull request merged**
