### PR TITLE
Set `@typespec/compiler` as a `peerDependency` in library templates

### PR DESCRIPTION
**Pull request by steverice**
As specified in [the documentation](https://typespec.io/docs/extending-typespec/basics#step-3-defining-dependencies):
> Use `peerDependencies` for all TypeSpec libraries (and the compiler) that you use in your own library or emitter.

### CODE REVIEW

**Comment by steverice** [comment]
@microsoft-github-policy-service agree company=“Pinterest"

**Review by timotheeguerin — APPROVED** [review]

**Comment by steverice** [comment]
@microsoft-github-policy-service agree company=“Pinterest"

**Review by sarangan12 — APPROVED** [review]
LGTM

**Comment by steverice** [comment]
Hey @sarangan12 , can we merge this?

**Pull request merged**
