### PR TITLE
Move doc for types into language-basics section

### PR DESCRIPTION
**Pull request by mikekistler**
This PR just moves the documentation of built-in types from the "Standard Library" section to the "Language Basics" section of the website docs.

### CODE REVIEW

**Comment by timotheeguerin** [comment]
Kinda made this section to talk about the different concept in the cadl language. 
Wondering if instead maybe we can move the libraries into another section and keep Standard Library as the built-in types and decorators

languages-basics:
   ... language concepts
standard library:
   built in types
   built in decorators
libraries:
   http
   rest
   openapi
   ...

**Comment by mikekistler** [comment]
Isn't it odd to include a section on scalars -- which can extend types -- and models -- which are structured collections of typed values -- before describing the basic types?  Or operations ... which take typed arguments and return a typed response?

I think there is just a basic ordering problem here.

**Comment by timotheeguerin** [comment]
Yeah it is a bit of a chicken and egg problem. I think at the very least here it is buried in the concept documentation. If we move it it should either be first of that section or be in another one

**Comment by mikekistler** [comment]
I can move it to right after the Overview -- I think the Overview should come first. How does that sound?

**Comment by timotheeguerin** [comment]
I think that would be better

**Review by timotheeguerin — APPROVED** [review]

**Pull request merged**
