### PR TITLE
Allow is and extends of a template parameter

### PR DESCRIPTION
**Pull request by bterlson**

### CODE REVIEW

**Comment by nguerrera** [comment]
This has the problem still where the error occurs on the template rather than the instantiation:

https://cadlplayground.z22.web.core.windows.net/prs/675/?c=bW9kZWwgVGVtcGxhdGU8VD4gZXh0ZW5kcyBUIHt9DQoNCsgic3Qgew0KICBwcm9wOsoyIsQaIj47DQp9

On https://github.com/microsoft/cadl/issues/423, we said this would be needed for this feature.

**Comment by nguerrera** [comment]
Mind you this is pre-existing for other cases:

https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgVGVtcGxhdGU8VD4gew0KICBwcm9wOiBUICYge30NCn0NCg0KxipNzSDINyJ0ZXN0Ij4NCn0%3D

And another bug, that error doesn't give a good location at all.

I'm not sure if we need to gate this change on it, but it adds more pressure to get this right. The experience is really confusing when we don't squiggle the root cause.

**Comment by nguerrera** [comment]
Filed https://github.com/microsoft/cadl/issues/676 for "another bug"

**Comment by nguerrera** [comment]
My only real concern is if we're tracking the elaboration work somewhere. I was sort of mentally mapping it to this feature as that's where I remembered discussing it. So I would say this can go in and we should have a distinct elaboration work item.

**Review by nguerrera — APPROVED** [review]

**Comment by markcowl** [comment]
@bterlson What do we need to do to get this incorporated or closed?

**Comment by bterlson** [comment]
I seem to recall that I became less convicned this was a good idea. Let me dig out the rationale as I did a bad job surfacing that info here.

**Pull request closed without merging**
